spring.application.name=cinemax
server.port=8081
# ----------------------------------------
# DATABASE CONFIGURATION (MySQL)
# ----------------------------------------
# Ganti 'cinemax_db' dengan nama database yang akan Anda buat di MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/cinemax_db?serverTimezone=Asia/Jakarta&useSSL=false
# Username XAMPP/MySQL
spring.datasource.username=root
# Password XAMPP/MySQL
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ----------------------------------------
# MAIL CONFIGURATION (Mailtrap)
# ----------------------------------------
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
# Silakan ganti username di bawah dengan username SMTP Inbox Mailtrap Anda
spring.mail.username=b4e5cdbf648b16
spring.mail.password=58dc34d9902e30
spring.mail.token=c6e81628322e76548e61d959ca158dec
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ----------------------------------------
# HIBERNATE & JPA CONFIGURATION
# ----------------------------------------
# 'update' akan secara otomatis men-generate/memodifikasi tabel di MySQL 
# berdasarkan Class (Entity) Java yang kita buat nanti. Sangat cocok untuk tahap awal (development).
spring.jpa.hibernate.ddl-auto=update
# Menampilkan sintaks SQL di terminal saat aplikasi berjalan (mempermudah debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ----------------------------------------
# CHARACTER ENCODING (Mencegah Mojibake)
# ----------------------------------------
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true
spring.thymeleaf.encoding=UTF-8

# Menampilkan error lengkap di browser
server.error.include-stacktrace=always
server.error.include-message=always
